# This file was generated by GoReleaser. DO NOT EDIT.
cask "langdock-mcp" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "59a54f5006d9770c022535138c5893db032a13d6e671fba9c2bd9a334d8aba39"
      url "https://github.com/dennisschroeder/langdock-mcp/releases/download/v#{version}/langdock-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f7383e0f94a3b0ff8b09a4a8e52f50220b800b78a44fe6da73b2bfd7847164f8"
      url "https://github.com/dennisschroeder/langdock-mcp/releases/download/v#{version}/langdock-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "05cd65340e7c1d50e464c95eb6b26be892a612aafcc3d9e126e6c6f8abd1a1ae"
      url "https://github.com/dennisschroeder/langdock-mcp/releases/download/v#{version}/langdock-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "38f9dc36d406a0a41683f3de9a74a4f3a5afba170d1567b4bc0543f35af3f54f"
      url "https://github.com/dennisschroeder/langdock-mcp/releases/download/v#{version}/langdock-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "langdock-mcp"
  desc "MCP server for the Langdock Integrations and Agents APIs"
  homepage "https://github.com/dennisschroeder/langdock-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "langdock-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/langdock-mcp"]
    end
  end

  # No zap stanza required
end
