# This file was generated by GoReleaser. DO NOT EDIT.
cask "langdock-mcp" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "56bb0f973b83eb7da9abdbff9bffbf776cec2d17bc5bc57af1cccacec8a28994"
      url "https://github.com/dennisschroeder/langdock-mcp/releases/download/v#{version}/langdock-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5425937fabbd179e47c1cd2900527f2cf739f1281e1df37c2912da2c4cc5939d"
      url "https://github.com/dennisschroeder/langdock-mcp/releases/download/v#{version}/langdock-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5452f766d059dfb94ab6613e654c83677b7fde8636a54597c077b94aa0e68f7f"
      url "https://github.com/dennisschroeder/langdock-mcp/releases/download/v#{version}/langdock-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f0b396294edab2a79cd12546c729747fc11cfbb6f6c966c66fd52fe98371294e"
      url "https://github.com/dennisschroeder/langdock-mcp/releases/download/v#{version}/langdock-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "langdock-mcp"
  desc "MCP server for the Langdock Integrations and Agents APIs"
  homepage "https://github.com/dennisschroeder/langdock-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "langdock-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/langdock-mcp"]
    end
  end

  # No zap stanza required
end
