# This file was generated by GoReleaser. DO NOT EDIT.
cask "langdock-mcp" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "61daa49d7f52949989117d1087bb141b23d0e26be73779919ea36cc2662b5412"
      url "https://github.com/dennisschroeder/langdock-mcp/releases/download/v#{version}/langdock-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "feb82cdb1c3e9c4857b72ad38d6d5c7ec5b2da22195d8ac1c6ef954bd20b7069"
      url "https://github.com/dennisschroeder/langdock-mcp/releases/download/v#{version}/langdock-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "84a60a09c6a395994baa7d4d7ab84fdc3e3b8c7d17ba5369b8c1339ed6684b48"
      url "https://github.com/dennisschroeder/langdock-mcp/releases/download/v#{version}/langdock-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2c9ce7b6666e7594a2926a7fa7817476c3103c60f4580ac4613a4181d9c1e127"
      url "https://github.com/dennisschroeder/langdock-mcp/releases/download/v#{version}/langdock-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "langdock-mcp"
  desc "MCP server for the Langdock Integrations and Agents APIs"
  homepage "https://github.com/dennisschroeder/langdock-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "langdock-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/langdock-mcp"]
    end
  end

  # No zap stanza required
end
